auth_enabled: false
chunk_store_config:
  max_look_back_period: 0
ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    interface_names: [tap0]
  max_transfer_retries: 0
limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 720h
  max_entries_limit_per_query: 0
schema_config:
  configs:
  - from: '2018-04-15'
    index:
      period: 168h
      prefix: index_
    object_store: filesystem
    schema: v9
    store: boltdb
server:
  http_listen_port: 3100
storage_config:
  boltdb:
    directory: "/tmp/loki/index"
  filesystem:
    directory: "/tmp/loki/chunks"
table_manager:
  retention_deletes_enabled: false
  retention_period: 0
